version: '3'

services:

  db:
    restart: always
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_DATABASE: moneyapi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  customerservice:
    image: my-app             #name of the image after dockerfile executes
    container_name: spring-boot-api  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8080:8080"                       #docker containter port with your os port
    restart: always

    depends_on: #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/moneyapi?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

