version: '3'

services:

  db:
    restart: always
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_DATABASE: moneyapi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  customerservice:
    image: my-app             
    container_name: spring-boot-api  
    build:
      context: .                          
      dockerfile: Dockerfile              
    ports:
      - "8080:8080"                     
    restart: always

    depends_on: 
      - db                                
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/moneyapi?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

